python main.py \
    --model_name=fno_2d \
    --loss_cfg=/workdir/PISeg/PISeg/cfgs/no.yaml \
    --metric_cfg=/workdir/PISeg/PISeg/cfgs/no-metrics.yaml \
    --logdir=/workdir/PISeg/PISeg/runs/128-512 \
    --num_cat=2 \
    --optim_lr=1e-3 \
    --lrschedule=warmup_cosine \
    --traindata_dir=/dataset/CXR/leftlungSZPreprocess_128x128/ \
    --valdata_dir=/dataset/CXR/leftlungSZPreprocess_512x512/ \
    --deterministic=1 \
    --max_epochs=2000 \
    --seed=2 \
    --batch_size=16 \
    --val_every=10 \
    --warmup_epochs=10 \
    --outsdf=1 \
    --workers=8 
